name: Deploy on AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run : |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/blog-backend:latest ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/blog-backend:latest

    - name: Build and push frontend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/blog-frontend:latest ./client
        docker push ${{ secrets.DOCKER_USERNAME }}/blog-frontend:latest  

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.AWS_EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.AWS_EC2_IP }} >> ~/.ssh/known_hosts

    - name: Deploy on AWS EC2 using Docker Compose
      run: |
        # Transfer the entire project (including backend, frontend, compose.yml)
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r . ubuntu@${{ secrets.AWS_EC2_IP }}:~/blog

        # Export GitHub secrets as environment variables
        export VITE_API_URL=${{ secrets.VITE_API_URL }} 
        export DB_CREDENTIALS="${{ secrets.DB_CREDENTIALS }}"       

        # SSH into EC2 and deploy the app
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_EC2_IP }} << 'EOF'
          # Check if Docker Compose is installed
          echo "Checking if Docker Compose is installed..."
          docker-compose --version || echo "docker-compose not found, proceeding with installation..."

          # Install Docker Compose if not installed
          if ! command -v docker-compose &> /dev/null; then
            echo "docker-compose not found, installing..."
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi

          # Check Docker Compose version
          docker-compose --version

          # Navigate to project directory
          cd ~/blog

          # Pull the latest Docker images for backend and frontend
          echo "Pulling latest Docker images..."
          docker pull ${{ secrets.DOCKER_USERNAME }}/blog-backend:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/blog-frontend:latest

          # Validate compose.yml file format
          echo "Validating compose.yml file..."
          docker-compose config || { echo "compose.yml validation failed!"; exit 1; }

          # Deploy the app with Docker Compose
          echo "Deploying app with Docker Compose..."
          docker-compose up -d --build
        EOF
